# A sample Guardfile
# More info at https://github.com/guard/guard#readme

# This will concatenate the javascript files specified in :files to public/js/all.js

group :all do
	guard :sass, :output => 'public' do
		watch(%r{^public/(.+\.s[ac]ss)$})
	end
	guard :jammit,
		:config_path => "public/assets.yml",
		:output_folder => "." do
		watch(%r{^public/(.+\.css)$}) { |m| m[0] unless m[1] =~ /\/\./ }
	end
end



guard 'changelog' do
	 watch('.*')
end
