redis:
  number: 2
  # 	  ^select a redis instance, default: 1
  mode: 0
  # 	1 = redis is running on a socket
  # 	0 = redis is running on a port
  socket: '/home/satar/.redis/sock' 
  host: '127.0.0.1'
  port: 6379

server:
  port: 42337
  # port for the ui web server
  bind: 0.0.0.0

sql:
  host: localhost
  user: root
  pw: satar
  db: satar-server # must exist, do not change for proper interaction with other scripts
  table: race_results # must exist, do not change for proper interaction with other scripts
  raceID: raceID # MySQL table column names for the results can be changed here,
  userID: userID # ^ this is useful for custom postprocessor,
  runtime: runtime # ^ most times these can be left at their default values.
  
# syslog: 
sql_log:
  host: localhost
  user: root
  pw: satar
  db: satar-debug # must exist, do not change for proper interaction with other scripts
  table: timelog # must exist, do not change for proper interaction with other scripts
  nodeID: nodeID # MySQL table column names for the results can be changed here,
  nodeDelta: nodeDelta # ^ this is useful for custom postprocessor,
  nodeDev: nodeDev # ^ most times these can be left at their default values.